---
kind: pipeline
type: docker
name: web

steps:
  - name: install cnpm
    image: node:alpine
    commands:
      - npm install -g cnpm

  - name: cnpm install
    image: node:alpine
    commands:
      - cnpm install

  - name: test
    image: node:alpine
    commands:
      - npm run test

  - name: build
    image: node:alpine
    commands:
      - npm run build

  - name: rsync production
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
    settings:
      hosts:
        - 106.12.49.47
      source: .vuepress/dist/*
      target: /home/doc
      secrets: [rsync_key]
    when:
      target:
        - production
      event:
        - promote

  - name: notify
    image: curlimages/curl
    commands:
      - |
        curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=e6ad01ff-7207-4183-abfa-4c89fa802177' -H 'Content-Type: application/json' -d '{"msgtype": "text", "text": {"content": "ok"}}'
    when:
      status:
        - failure
        - success
